[Interface]
PrivateKey = 4xLOu9evII1KUR/Oqugf3u2T37iIVompons3JsvnGmQ=
Address = 10.13.13.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = k/KlE0f+Sl1b7DXvccx0HGas4mc6+7i1v5kZlISGzWM=
Endpoint = YOUR_PUBLIC_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
